basePath: /api
host: localhost:8080
info:
  contact:
    email: aji@example.com
    name: API Support
  description: Layanan backend untuk sistem check-in dan check-out terintegrasi Kafka.
  termsOfService: http://swagger.io/terms/
  title: API Presensi Karyawan
  version: "1.0"
paths:
  /check-in:
    post:
      consumes:
      - application/json
      description: Endpoint untuk mencatat waktu check-in pengguna.
      produces:
      - application/json
      responses:
        "200":
          description: Check-in berhasil
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request / Gagal Check-in
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Melakukan presensi masuk
      tags:
      - Attendance
  /check-out:
    post:
      consumes:
      - application/json
      description: Endpoint untuk mencatat waktu check-out pengguna.
      produces:
      - application/json
      responses:
        "200":
          description: Check-out berhasil
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request / Gagal Check-out
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Melakukan presensi pulang
      tags:
      - Attendance
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Endpoint untuk mendapatkan token JWT dengan email.
      parameters:
      - description: 'Email pengguna (misal: aji@example.com)'
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Token berhasil dibuat
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Email tidak terdaftar
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Gagal membuat token
          schema:
            additionalProperties: true
            type: object
      summary: Login Pengguna
      tags:
      - Auth
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Endpoint untuk mengambil data user berdasarkan ID.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Data user
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ID tidak valid
          schema:
            additionalProperties: true
            type: object
        "404":
          description: User tidak ditemukan
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Mendapatkan detail user
      tags:
      - Users
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
